#!/usr/bin/env bash
# Cursor Cloud start for DealDex.  Runs each agent boot.
# Loads Infisical secrets into $HOME/.cursor-cloud-env/dealdex.env when
# Cursor dashboard provides INFISICAL_CLIENT_ID + INFISICAL_CLIENT_SECRET.
# Never prints secret VALUES.  Missing credentials exit 0 with NAMES only.
set -euo pipefail

cd "$(dirname "$0")/.."
REPO_ROOT="$(pwd)"
ENV_DIR="${HOME}/.cursor-cloud-env"
ENV_FILE="${ENV_DIR}/dealdex.env"
SOURCE_FILE="${ENV_DIR}/dealdex.source.sh"

mkdir -p "$ENV_DIR"
chmod 700 "$ENV_DIR" 2>/dev/null || true

log() { printf '==> %s\n' "$*"; }

if [ -f "$REPO_ROOT/.cursor/infisical.env" ]; then
  set -a
  # shellcheck disable=SC1091
  . "$REPO_ROOT/.cursor/infisical.env"
  set +a
fi

: "${INFISICAL_ENV:=dev}"
: "${INFISICAL_DOMAIN:=https://app.infisical.com}"

MISSING=()
[ -z "${INFISICAL_CLIENT_ID:-}" ] && MISSING+=("INFISICAL_CLIENT_ID")
[ -z "${INFISICAL_CLIENT_SECRET:-}" ] && MISSING+=("INFISICAL_CLIENT_SECRET")
if [ "${#MISSING[@]}" -gt 0 ]; then
  log "Infisical credentials not configured in the Cursor dashboard."
  log "Add these secrets to the Cursor dashboard (org-wide / team):"
  for name in "${MISSING[@]}"; do log "  - ${name}"; done
  exit 0
fi

if [ -z "${INFISICAL_PROJECT_ID:-}" ]; then
  log "INFISICAL_PROJECT_ID missing from .cursor/infisical.env; skipping secret load."
  exit 0
fi

export INFISICAL_CLIENT_ID INFISICAL_CLIENT_SECRET INFISICAL_PROJECT_ID INFISICAL_ENV INFISICAL_DOMAIN
export CURSOR_CLOUD_ENV_OUT="$ENV_FILE"

python3 - <<'PY'
import json, os, shlex, stat, sys, tempfile, urllib.error, urllib.parse, urllib.request
from pathlib import Path

out = Path(os.environ["CURSOR_CLOUD_ENV_OUT"])
domain = os.environ["INFISICAL_DOMAIN"].rstrip("/")
client_id = os.environ["INFISICAL_CLIENT_ID"]
client_secret = os.environ["INFISICAL_CLIENT_SECRET"]
project_id = os.environ["INFISICAL_PROJECT_ID"]
environment = os.environ["INFISICAL_ENV"]

def http_json(method, url, body=None, headers=None):
    data = None if body is None else json.dumps(body).encode()
    req = urllib.request.Request(url, data=data, method=method, headers=headers or {})
    if data is not None:
        req.add_header("Content-Type", "application/json")
    with urllib.request.urlopen(req, timeout=60) as resp:
        return json.load(resp)

try:
    login = http_json(
        "POST",
        f"{domain}/api/v1/auth/universal-auth/login",
        {"clientId": client_id, "clientSecret": client_secret},
    )
    token = login.get("accessToken") or ""
    if not token:
        print("==> Infisical login returned no accessToken", file=sys.stderr)
        sys.exit(1)
    qs = urllib.parse.urlencode(
        {
            "workspaceId": project_id,
            "environment": environment,
            "secretPath": "/",
            "include_imports": "true",
            "viewSecretValue": "true",
        }
    )
    payload = http_json(
        "GET",
        f"{domain}/api/v3/secrets/raw?{qs}",
        headers={"Authorization": f"Bearer {token}"},
    )
except urllib.error.HTTPError as exc:
    print(f"==> Infisical HTTP {exc.code}", file=sys.stderr)
    sys.exit(1)
except Exception as exc:  # noqa: BLE001 — names only, never values
    print(f"==> Infisical fetch failed: {type(exc).__name__}", file=sys.stderr)
    sys.exit(1)

items = payload.get("secrets") if isinstance(payload, dict) else payload
if not isinstance(items, list):
    items = []

lines = [f"# Generated by scripts/cursor-cloud-start.sh"]
count = 0
for item in items:
    if not isinstance(item, dict):
        continue
    key = item.get("secretKey") or item.get("key")
    value = item.get("secretValue")
    if not key or value is None:
        continue
    lines.append(f"{key}={shlex.quote(str(value))}")
    count += 1

out.parent.mkdir(parents=True, exist_ok=True)
fd, tmp_name = tempfile.mkstemp(prefix=".dealdex.env.", dir=str(out.parent))
try:
    with os.fdopen(fd, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    os.chmod(tmp_name, stat.S_IRUSR | stat.S_IWUSR)
    os.replace(tmp_name, out)
except Exception:
    try:
        os.unlink(tmp_name)
    except OSError:
        pass
    raise

print(f"==> Infisical secrets loaded for {environment} ({count} keys) → {out}")
PY

cat > "$SOURCE_FILE" <<'SRC'
# Source this to inherit Cursor-loaded Infisical secrets for DealDex.
[ -f "${HOME}/.cursor-cloud-env/dealdex.env" ] || return 0
set -a
. "${HOME}/.cursor-cloud-env/dealdex.env"
set +a
SRC
chmod 600 "$SOURCE_FILE"
exit 0
