#!/usr/bin/env bash
# Cursor cloud start for DealDex (plumber/cursor-cloud-env).
# Runs on every agent boot.  Cursor dashboard injects INFISICAL_CLIENT_ID
# and INFISICAL_CLIENT_SECRET as env vars; this script fetches the
# configured snapshot for DealDex and writes it to:
#   $HOME/.cursor-cloud-env/dealdex.env          (mode 0600, KEY=VALUE)
#   $HOME/.cursor-cloud-env/dealdex.source.sh    (sources the file)
# so subsequent shell steps can `source` the file without ever printing
# values.
#
# Reuses scripts/infisical-fetch.mjs for the universal-auth login + raw
# secrets list (same code path the CI workflows use); only the file
# serializer is new.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${REPO_ROOT}"

log() { printf '[cursor-cloud-start] %s\n' "$*"; }

# 0.  Load the committed per-repo non-secrets (PROJECT_ID + ENV + DOMAIN).
INFISICAL_ENV_FILE="${REPO_ROOT}/.cursor/infisical.env"
if [[ ! -f "${INFISICAL_ENV_FILE}" ]]; then
  log "Missing ${INFISICAL_ENV_FILE}; aborting."
  exit 1
fi
# shellcheck disable=SC1090
set -a
. "${INFISICAL_ENV_FILE}"
set +a

# 1.  Honour the only populated Infisical env for this project.
: "${INFISICAL_PROJECT_ID:?INFISICAL_PROJECT_ID missing in .cursor/infisical.env}"
: "${INFISICAL_ENV:=dev}"
: "${INFISICAL_DOMAIN:=https://app.infisical.com}"
export INFISICAL_PROJECT_ID INFISICAL_ENV INFISICAL_DOMAIN

# 2.  When Cursor has injected the automation machine identity, fetch the
#     snapshot and write it.  Missing credentials is the normal
#     pre-dashboard-add state -- exit 0 with a clear message naming the
#     missing dashboard secret NAMES so the coordinator can add them.
if [[ -z "${INFISICAL_CLIENT_ID:-}" || -z "${INFISICAL_CLIENT_SECRET:-}" ]]; then
  log "INFISICAL_CLIENT_ID or INFISICAL_CLIENT_SECRET not set in the Cursor dashboard."
  log "Add these org-wide / team secrets to the Cursor dashboard:"
  log "  - INFISICAL_CLIENT_ID"
  log "  - INFISICAL_CLIENT_SECRET"
  log "Until then, .env loading is skipped (exit 0)."
  exit 0
fi

OUT_DIR="${HOME}/.cursor-cloud-env"
OUT_ENV="${OUT_DIR}/dealdex.env"
OUT_SRC="${OUT_DIR}/dealdex.source.sh"
mkdir -p "${OUT_DIR}"
chmod 700 "${OUT_DIR}"

log "Fetching Infisical ${INFISICAL_ENV} secrets for DealDex into ${OUT_ENV}."

# 3.  Reuse the CI fetch library.  We only need the raw map, so import the
#     two pure helpers directly and serialize to a KEY=VALUE .env.
TMP_ENV_FILE="$(mktemp -t cursor-cloud-dealdex.XXXXXX)"
trap 'rm -f "${TMP_ENV_FILE}"' EXIT

node --input-type=module -e "
import { loginUniversalAuth, listSecretsRaw } from './scripts/infisical-fetch.mjs';
import { writeFileSync, chmodSync } from 'node:fs';

const siteUrl = String(process.env.INFISICAL_DOMAIN || 'https://app.infisical.com').replace(/\/+\$/, '');
const clientId = process.env.INFISICAL_CLIENT_ID;
const clientSecret = process.env.INFISICAL_CLIENT_SECRET;
const projectId = process.env.INFISICAL_PROJECT_ID;
const environment = process.env.INFISICAL_ENV;
const secretPath = process.env.INFISICAL_SECRET_PATH || '/';

const token = await loginUniversalAuth({ siteUrl, clientId, clientSecret });
const values = await listSecretsRaw({ siteUrl, token, projectId, environment, secretPath });

// Serialize as a shell-safe KEY=VALUE file.  Quote every value with single
// quotes and escape any embedded single quotes -- a bare value containing
// \`=\`, spaces, or newlines would break downstream consumers otherwise.
let body = '# Generated by scripts/cursor-cloud-start.sh -- do not edit.\n';
for (const [key, val] of values.entries()) {
  if (!/^[A-Za-z_][A-Za-z0-9_]*\$/.test(key)) continue;
  const escaped = String(val).replace(/'/g, \"'\\\\''\");
  body += key + \"='\" + escaped + \"'\\n\`;
}
writeFileSync(process.argv[1], body, { mode: 0o600 });
chmodSync(process.argv[1], 0o600);
" "${TMP_ENV_FILE}" >/dev/null 2>&1 || {
  log "Infisical fetch failed; skipping .env write (exit 0)."
  exit 0
}

# Atomic move into place, then re-assert 0600 (cp / shell tooling can
# occasionally leave the file at 0644 after a cross-filesystem copy).
mv "${TMP_ENV_FILE}" "${OUT_ENV}"
chmod 0600 "${OUT_ENV}"
trap - EXIT

# 4.  Tiny source script for downstream shells -- never prints values.
cat >"${OUT_SRC}" <<'EOS'
# Auto-generated by scripts/cursor-cloud-start.sh.
# Sources dealdex.env with allexport on so every KEY=VALUE enters the
# environment without printing.
set -a
. "${HOME}/.cursor-cloud-env/dealdex.env"
set +a
EOS
chmod 0600 "${OUT_SRC}"

log "Wrote ${OUT_ENV} (mode 0600) and ${OUT_SRC}."
exit 0