#!/usr/bin/env bash
# Cursor Cloud start for DealDex.  Runs each agent boot.
# Loads Infisical secrets for INFISICAL_ENV into $HOME/.cursor-cloud-env/
# when Cursor dashboard secrets INFISICAL_CLIENT_ID + INFISICAL_CLIENT_SECRET
# are present.  Exits 0 (never fails the boot) and never prints secret VALUES.
set -euo pipefail

cd "$(dirname "$0")/.."

REPO_ROOT="$(pwd)"
REPO_NAME="dealdex"

ENV_DIR="${HOME}/.cursor-cloud-env"
ENV_FILE="${ENV_DIR}/${REPO_NAME}.env"
SOURCE_FILE="${ENV_DIR}/${REPO_NAME}.source.sh"

mkdir -p "$ENV_DIR"
chmod 700 "$ENV_DIR" 2>/dev/null || true

log() { printf '==> %s\n' "$*"; }

# --- Project identity (committed in .cursor/infisical.env) ------------------
PROJECT_ID=""
INFISICAL_ENV="dev"
INFISICAL_DOMAIN="https://app.infisical.com"

if [ -f "$REPO_ROOT/.cursor/infisical.env" ]; then
  # shellcheck disable=SC1090
  set -a; . "$REPO_ROOT/.cursor/infisical.env"; set +a
fi

if [ -z "${PROJECT_ID:-}" ] && [ -n "${INFISICAL_PROJECT_ID:-}" ]; then
  PROJECT_ID="$INFISICAL_PROJECT_ID"
fi

# --- Guard: missing dashboard secrets ---------------------------------------
# We must NEVER print secret VALUES.  If Cursor dashboard has not been
# configured yet, name the missing keys and exit 0 so the agent boot still
# succeeds (DealDex's server falls back to process.env + built-in defaults
# per INFISICAL.md, so dev still works without Infisical).
MISSING=()
if [ -z "${INFISICAL_CLIENT_ID:-}" ]; then
  MISSING+=("INFISICAL_CLIENT_ID")
fi
if [ -z "${INFISICAL_CLIENT_SECRET:-}" ]; then
  MISSING+=("INFISICAL_CLIENT_SECRET")
fi

if [ "${#MISSING[@]}" -gt 0 ]; then
  log "Infisical credentials not configured in the Cursor dashboard."
  log "Add these secrets to the Cursor dashboard (org-wide / team):"
  for name in "${MISSING[@]}"; do
    log "  - ${name}"
  done
  log "Until then the server runs in local-only mode (process.env + defaults)."
  exit 0
fi

if [ -z "$PROJECT_ID" ]; then
  log "INFISICAL_PROJECT_ID not set (expected in .cursor/infisical.env); skipping secret load."
  exit 0
fi

# --- Helper that fetches and writes secrets atomically -----------------------
# Always writes via a temp file (mode 0600) + mv so partial writes never
# leave the env file readable mid-rotation.  Values stay on disk only — never
# echoed to stdout.
fetch_and_write() {
  local tmp
  tmp="$(mktemp "${ENV_DIR}/.${REPO_NAME}.env.tmp.XXXXXX")"
  chmod 600 "$tmp"

  # Path 1: official CLI — acquire a short-lived universal-auth token, then
  # export the project's dotenv into the temp file.  No VALUES are ever
  # echoed; the CLI writes the file directly.
  if command -v infisical >/dev/null 2>&1; then
    local token=""
    token="$(infisical login \
        --method=universal-auth \
        --client-id="$INFISICAL_CLIENT_ID" \
        --client-secret="$INFISICAL_CLIENT_SECRET" \
        --domain="$INFISICAL_DOMAIN" \
        --silent --plain 2>/dev/null || true)"
    if [ -n "$token" ] && [ "${#token}" -gt 16 ]; then
      if infisical export \
            --token "$token" \
            --projectId "$PROJECT_ID" \
            --env "$INFISICAL_ENV" \
            --domain "$INFISICAL_DOMAIN" \
            --format=dotenv \
            --includeSecrets=true > "$tmp" 2>/tmp/infisical-export.err; then
        printf '%s\n' "# Generated by scripts/cursor-cloud-start.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$tmp"
        mv "$tmp" "$ENV_FILE"
        chmod 600 "$ENV_FILE"
        rm -f /tmp/infisical-export.err
        token=""
        return 0
      fi
      rm -f /tmp/infisical-export.err
      log "Infisical CLI export failed; falling back to REST API."
    else
      log "Infisical CLI login returned no token; falling back to REST API."
    fi
    rm -f "$tmp"
    tmp="$(mktemp "${ENV_DIR}/.${REPO_NAME}.env.tmp.XXXXXX")"
    chmod 600 "$tmp"
  fi

  # Path 2: REST fallback.  The /api/v3/secrets/raw endpoint returns every
  # secret VALUE in one JSON response — using it per-key (the previous bug)
  # sometimes wrote 0 keys when the list call failed.  One round-trip + one
  # python3 pass that writes KEY=VALUE lines directly to the temp file with
  # proper shell quoting.  Values never cross python3's stdout.
  local bearer=""
  bearer="$(printf '{"clientId":"%s","clientSecret":"%s"}' \
      "$INFISICAL_CLIENT_ID" "$INFISICAL_CLIENT_SECRET" \
    | curl -fsS \
        -X POST "${INFISICAL_DOMAIN}/api/v1/auth/universal-auth/login" \
        -H 'Content-Type: application/json' \
        --data-binary @- \
    | python3 -c 'import json,sys; print(json.load(sys.stdin).get("accessToken",""))' 2>/dev/null || true)"
  if [ -z "$bearer" ]; then
    rm -f "$tmp"
    return 1
  fi

  curl -fsS \
      -H "Authorization: Bearer ${bearer}" \
      "${INFISICAL_DOMAIN}/api/v3/secrets/raw?environment=${INFISICAL_ENV}&workspaceId=${PROJECT_ID}&secretPath=/&include_imports=true" \
    | python3 - "$tmp" <<'PY' || { rm -f "$tmp"; bearer=""; return 1; }
import json, sys, shlex
out_path = sys.argv[1]
with open(out_path, "a") as fh:
    payload = json.load(sys.stdin)
    # v3 raw can return {"secrets":[{secretKey, secretValue}, ...]} or a flat list.
    items = payload.get("secrets") if isinstance(payload, dict) else payload
    if not isinstance(items, list):
        items = []
    for entry in items:
        if not isinstance(entry, dict):
            continue
        key = entry.get("secretKey", "")
        value = entry.get("secretValue", "")
        if not key:
            continue
        fh.write(f"{key}={shlex.quote(value)}\n")
PY

  printf '%s\n' "# Generated by scripts/cursor-cloud-start.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  chmod 600 "$ENV_FILE"
  # Drop the bearer from memory; nothing else held it.
  bearer=""
  return 0
}

if fetch_and_write; then
  log "Infisical secrets loaded for ${INFISICAL_ENV} → ${ENV_FILE}"
else
  log "Failed to load Infisical secrets; server will run in local-only mode."
fi

# --- Companion source script -------------------------------------------------
# A tiny shim that other shells can source to inherit the env file without
# printing anything.  `set -a` exports every assigned variable; the file
# itself is mode 0600 and owned by the agent user.
cat > "$SOURCE_FILE" <<'EOF'
# Source this to inherit Cursor-loaded Infisical secrets for DealDex.
# Generated by scripts/cursor-cloud-start.sh — do not edit by hand.
[ -f "${HOME}/.cursor-cloud-env/dealdex.env" ] || return 0
set -a
. "${HOME}/.cursor-cloud-env/dealdex.env"
set +a
EOF
chmod 600 "$SOURCE_FILE"

exit 0